# Generated by Django 5.2.6 on 2025-09-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_bill_billitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
    ]
