# Generated by Django 5.2.6 on 2025-09-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_billitem_subtotal_alter_bill_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='staff',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
    ]
