# Generated by Django 5.2.6 on 2025-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_customuser_role_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
