# Generated by Django 5.2.6 on 2025-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_supplierrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
